export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const QR_LOGIN_START = 'QR_LOGIN_START';
export const QR_LOGIN_SUCCESS = 'QR_LOGIN_SUCCESS';
export const QR_LOGIN_FAIL = 'QR_LOGIN_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const SET_USER = 'SET_USER';

export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS';
export const GOOGLE_SIGN_IN_FAIL = 'GOOGLE_SIGN_IN_FAIL';

////////////////////////////////////////////////////////////////

export const GET_USER_BY_ID_START = 'GET_USER_BY_ID_START'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL'

export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL ='GET_USERS_FAIL'

export const GET_EXCURTIONS_START = 'GET_EXCURTIONS_START'
export const GET_EXCURTIONS_SUCCESS = 'GET_EXCURTIONS_SUCCESS'
export const GET_EXCURTIONS_FAIL = 'GET_EXCURTIONS_FAIL'

export const GET_ALL_IMAGES_START = 'GET_ALL_IMAGES_START'
export const GET_ALL_IMAGES_SUCCESS = 'GET_ALL_IMAGES_SUCCESS'
export const GET_ALL_IMAGES_FAIL = 'GET_ALL_IMAGES_FAIL'
